### ISSUE TITLE
Merge conda-package-streaming and conda-package-handling teams

### ISSUE THREAD

**Issue by dholth** [conda/infrastructure#1007]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

There is a separate conda-package-streaming team, and a separate conda-index team. These do not have enough members.

Merge with the amorphus team managing conda-package-handling?

**Comment by jezdez** [comment]
For the record, the teams are separate for historic reasons, as a reminder, per governance policy:

> A Project Team is a [sub-team](https://github.com/conda/infrastructure/issues/1007#sub-teams) with a [dynamic charter](https://github.com/conda/infrastructure/issues/1007#dynamic-charter), except for a few caveats as detailed here. They exist to maintain a specific project (**or possibly set of projects**). Each project in conda or conda-incubator should belong to exactly one Project Team.

`conda-package-handling` is being owned by the legacy conda-core team, which is bound to be deprecated in favor of a more fine-grained set of project teams. See for example the ticket about moving conda/conda into a community project team: https://github.com/conda/conda/issues/13526

`conda-package-streaming` is maintained by a community project team, and graduated the project in https://github.com/conda/conda-package-streaming/issues/31 to the main conda organization.

My suggestion is basically to:

- [ ] 1. move `conda-package-handling` into the custody of the current @conda/conda-package-streaming team,
- [ ] 2. rename the team to accommodate the increased team scope to `@conda/package-tools`, and
- [ ] 3. add the existing maintainers of conda-package-handling as members to the new combined `@conda/package-tools` team

The following people with access to conda-package-handling have to agree (please check the checkbox if you agree, or comment if you abstain or disagree):

- [ ] Members of @conda/conda-core:
	- [ ] @jezdez
	- [ ] @dholth
	- [ ] @travishathaway
	- [ ] @chenghlee
	- [ ] @kenodegard
	- [ ] @pseudoyim
	- [ ] @marcoesters
	- [ ] @beeankha
	- [ ] @ForgottenProgramme

- [ ] Members of @conda/community-contributors:
	- [ ] @marcelotrevisani
	- [ ] @mbargull

- [ ] 5. Additional individual contributors:
	- [ ] @jcrist
	- [ ] @msarahan

**Comment by marcelotrevisani** [comment]
The checkbox is not working for me but I agree.

**Comment by jezdez** [comment]
> The checkbox is not working for me but I agree.

Thanks for letting me know

**Comment by jezdez** [comment]
Quick update:

I've done the above TODOs and added @travishathaway @kenodegard @marcelotrevisani @marcoesters to the conda-package-handling team, now renamed @conda/packaging-tools.

I've also removed from the conda-package-handling repo: @jcrist @mbargull @msarahan @conda/conda-core.

Opened https://github.com/conda/conda-package-handling/pull/263 and https://github.com/conda/conda-package-streaming/pull/103

**Comment by jezdez** [comment]
Closing as done.
