### ISSUE TITLE
Do we remove the old `sync.yml` workflow?

### ISSUE THREAD

**Issue by kenodegard** [conda/infrastructure#1016]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Should we force all conda org repositories to use the new `update.yml` workflow? And then delete the old `sync.yml` workflow from here?

We have successfully migrated most repositories over to the new `update.yml` workflow. Those that remain are those that only sync the `CODE_OF_CONDUCT.md` and adding the `update.yml` workflow to those repositories is somewhat over the top.

### Why is this needed?

To delete old/unused code.

### What should happen?

Decide whether to force the new `update.yml` workflow on all repositories in the conda org.

**Comment by jezdez** [comment]
Personally I'd rather stick to one code infrastructure for this, instead of two, even if it feels over the top to just sync the CoC document, it's still a smaller effort to use the same system and rely on fewer 3rd party dependencies.

**Comment by kenodegard** [comment]
Just initiated both [conda-lock](https://github.com/conda/conda-lock/pull/716) and [grayskull](https://github.com/conda/grayskull/pull/568)
