### ISSUE TITLE
Add `rapidsai` channel to CDN

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#1055]
### Checklist

- [x] I added a descriptive title
- [x] I searched open requests and couldn't find a duplicate

### What is the idea?

Previously we had looked into setting up the CDN for [the `rapidsai` channel]( https://anaconda.org/rapidsai ). However it sounds like this work was never completed ( https://github.com/conda/infrastructure/issues/945#issuecomment-2425944242 ). Raising this issue to track enabling the CDN for `rapidsai`.

### Why is this needed?

Users regularly download packages from this channel. This will help reduce the load on Anaconda's servers and provide a better user experience.

### What should happen?

Things to check:
* [x] `rapidsai` only is available on CDN
* [ ] Ensure `.conda` packages can be downloaded from CDN (for example: [`xgboost`]( https://anaconda.org/rapidsai/xgboost/files ))
* [ ] Ensure `.conda` download counts are still picked up (for example: [`xgboost`]( https://anaconda.org/rapidsai/xgboost/files ))

### Additional Context

Note: `rapidsai-nightly` should **not** be on CDN

**Comment by jakirkham** [comment]
cc @morremeyer @jezdez @raydouglass

**Comment by jezdez** [comment]
Thanks for bringing this up, I've started an internal conversation about this

**Comment by jakirkham** [comment]
Thanks Jannis! 🙏

**Comment by jezdez** [comment]
@jakirkham We're ready to flip the switch for the rapidsai channel, do you prefer doing that before Thanksgiving, or after?

**Comment by jezdez** [comment]
> Thanks Jannis! 🙏
> 
> That's great news 😄
> 
> Let's do it the Monday after (so Dec 2nd)
> 
> Please let me know when it is enabled so we can start kicking the tires 🙂

Will do!

**Comment by jezdez** [comment]
The plan is to switch Dec 2, 10 am UTC

**Comment by jakirkham** [comment]
SGTM. Thanks Jannis! 🙏

**Comment by morremeyer** [comment]
We have switched the channel to be served from the cloning infrastructure now. 

Happy kicking!

**Comment by jakirkham** [comment]
Just wanted to update and say so far this is going well 😄

Tested this a bit before the RAPIDS 24.12 release by using 24.10 packages and trying `.conda` as well as legacy `.tar.bz2`, which worked well

Have also tested with RAPIDS 24.12 (recently pushed), which is working nicely! 🥳

Do want to keep an eye on download counts as that has been an issue in the past ( https://github.com/ContinuumIO/anaconda-package-data/issues/45 ), but we can track that separately

Will go ahead and close this out. Thank you again! 🙏
