### ISSUE TITLE
Corrupted package `linux-aarch64/r-base-4.4.1-h47223e1_16.conda` on CDN (original looks ok)

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#1067]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

When checking the channel normally (via CDN), am seeing the expected error (given this issue)

```
% conda search -c conda-forge "r-base[subdir=linux-aarch64]=4.4.1=h47223e1_16" 
Loading channels: done
No match found for: r-base==4.4.1=h47223e1_16[subdir=linux-aarch64]. Search: *r-base*==4.4.1=h47223e1_16[subdir=linux-aarch64]

PackagesNotFoundError: The following packages are not available from current channels:

  - r-base==4.4.1=h47223e1_16[subdir=linux-aarch64]

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-aarch64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

However when bypassing the CDN (by passing a label), the package is found

```
% conda search -c conda-forge/label/main "r-base[subdir=linux-aarch64]=4.4.1=h47223e1_16"               
Loading channels: done
# Name                       Version           Build  Channel             
r-base                         4.4.1     h47223e1_16  conda-forge/label/main
```

Has this package gotten corrupted on CDN?

### Additional Context

Originally from issue: https://github.com/conda-forge/r-base-feedstock/issues/357

Also relevant: https://github.com/conda-forge/admin-requests/pull/1176

**Comment by jakirkham** [comment]
@jezdez do you know if someone would be able to look into this one?

Given this `r-base` for Linux ARM, this is affecting quite a few people

**Comment by jezdez** [comment]
I've brought it up internally.

**Comment by jezdez** [comment]
I found that the original file doesn't exist in the conda-forge channel, was this somehow deleted? I see there is also a `[r-base-4.4.2-h47223e1_0.conda](https://anaconda.org/conda-forge/r-base/4.4.2/download/linux-aarch64/r-base-4.4.2-h47223e1_0.conda)` with the same hash?

![Image](https://github.com/user-attachments/assets/9eec2ed9-46dd-4387-833a-6c6d2cad7fbe)

The channel cloning process also highlights that the original file doesn't exist.

![Image](https://github.com/user-attachments/assets/93b4b630-b109-409e-941d-88ceaabf2d78)

This smells like a file deletion that wasn't correctly recorded in the database.

**Comment by jezdez** [comment]
Ah, seems like the upload didn't succeed in the first place, but a database record was created:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1047933&view=logs&j=6494c7a6-a019-59a3-6f3d-9bab8ca96717&t=18c91bca-a25a-5f89-34d4-93bbec4021bc&l=11667

![Image](https://github.com/user-attachments/assets/79f01154-495f-40cf-ab8c-58c935958d19)

**Comment by jezdez** [comment]
Since the file was never uploaded successfully, could you mark the version as broken and/or upload it again?

**Comment by jakirkham** [comment]
Thanks Jannis! 🙏

Yep sounds good. Closing this issue
