### ISSUE TITLE
DDoS attack against anaconda.org

### ISSUE THREAD

**Issue by chenghlee** [conda/infrastructure#1081]
Anaconda has been notified by our CDN provider of an DDoS attack against [anaconda.org](http://anaconda.org/); at this time, it appears that downloads from larger channels like conda-forge & bioconda are unaffected, but package uploads, downloads from smaller channels, and other API requests are failing.

For updates, please check: https://anaconda.statuspage.io/

**Comment by jakirkham** [comment]
Thanks Cheng! 🙏

Appreciate keeping us updated and the work to resolve the issue 🙂

Should we close this out now?

**Comment by chenghlee** [comment]
CDN DDoS protection measures have been put into place, and the various anaconda.org services have recovered to normal operating status. Closing this issue.

**Comment by jakirkham** [comment]
Think we can now unpin this one as well
