### ISSUE TITLE
Automate more with CLA bot

### ISSUE THREAD

**Issue by jezdez** [conda/infrastructure#538]
The conda GitHub org uses the [conda-bots](https://github.com/conda/conda-bots) codebase to run the @anaconda-issue-bot account which checks the https://github.com/conda/clabot-config/blob/master/.clabot file (not to be confused with the https://github.com/clabot project) whenever a contributor opens a pull request.

We should instead implement this as a GitHub action to be run whenever a new PR is opened.

Upsides: Some features of the conda-bots code was never fully used, and we'd save money and effort if we'd switch off the Heroku app for anaconda-issue-bot.

### Tasks

- [x] conda/infrastructure#548
- [x] conda/infrastructure#564
- [x] conda/actions#76
- [ ] Add new conda/cla team with CLA reviewers.
- [ ] *request a code review* from the conda team for the PR to signal to the team that a CLA review is needed (by checking the Adobe Sign mailbox)

**Comment by kenodegard** [comment]
Superseded by https://github.com/conda/cla/issues/1
