### ISSUE TITLE
Include PRs in issue sorting

### ISSUE THREAD

**Issue by jezdez** [conda/infrastructure#606]
### What is the idea?

We have a gap in coverage for the issue sorting, missing PRs in conda and conda-build, and having negative experience for contributors.

A slight tangent is an observation that issue sorting occurs in inconsistent waves. It would be valuable to add additional metrics to https://github.com/conda/issue-tracker to track the success of responding to tickets.

### Why is this needed?

Community PRs aren't being reviewed or responded to without extra prodding.

### What should happen?

We need a plan for how community PRs get addressed in a timely fashion.

**Comment by kenodegard** [comment]
The team has updated our processes and sought to include PRs in our sorting rotation. An effort has been underway to review older PRs and close them out if they are sufficiently stale (the fewer PRs we have open, the harder it'll be for PRs to slip through the cracks). We have also split out PRs into a new [Review project](https://github.com/orgs/conda/projects/16) which, at least for me, has helped improve searchability (https://github.com/conda/infrastructure/issues/696).

Are there other actions we can take on this? Or should we consider this addressed for now?

**Comment by jezdez** [comment]
I think this should be considered addressed, agreed that the new policies help solve the problem that led to creating this ticket.
