### ISSUE TITLE
Download counts missing python 3.10+ versions

### ISSUE THREAD

**Issue by wolfv** [conda/infrastructure#660]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I've noticed that the download counts (used e.g. by the `conda-stats` project or `by-the-numbers` of conda-forge) do not contain stats for the python variants >=3.10. That means that the numbers for certain packages with Python variants (e.g. `numpy`) will start to become less and less reliable (they are already pretty weird), because people are using 3.10 and higher base python versions.

### Conda Info

```shell
-
```

### Conda Config

```shell
-
```

### Conda list

```shell
-
```

**Comment by jakirkham** [comment]
Maybe we should move to [this repo]( https://github.com/ContinuumIO/anaconda-package-data )

**Comment by jezdez** [comment]
Yeah, I think that's right, the conda infra group isn't maintaining anaconda-package-data

**Comment by jaimergp** [comment]
What about a `conda/issues` meta-tracker, whose only purpose is having a good README + an Issue submission template pointing to the adequate repos?

**Comment by jezdez** [comment]
> What about a `conda/issues` meta-tracker, whose only purpose is having a good README + an Issue submission template pointing to the adequate repos?

Question, is who'd be doing the regular issue sorting on this.

@sophiamyang Should we recreate this in https://github.com/ContinuumIO/anaconda-package-data?

**Comment by wolfv** [comment]
I think the downloads for `.conda` packages are also missing whcih is why current download numbers are really low, btw :)

**Comment by sophiamyang** [comment]
Yes, looks like an issue for https://github.com/ContinuumIO/anaconda-package-data. @cappadona is maintaining the download pipeline.

**Comment by jezdez** [comment]
Closing in favor of https://github.com/ContinuumIO/anaconda-package-data/issues/41
