### ISSUE TITLE
Update HOW_WE_USE_GITHUB Document

### ISSUE THREAD

**Issue by travishathaway** [conda/infrastructure#677]
### What is the idea?

We have recently agreed to slightly refine our issue sorting process and would like to accordingly update this document:

- https://github.com/conda/infra/blob/main/HOW_WE_USE_GITHUB.md

### What should happen?

Add the following:

- [ ] Instructions on how to assign yourself to a ticket you are actively reviewing
- [ ] Instructions for how to use the `source::*` labels
- [ ] Add some more instructions for how to write an answer to an issue, revise the existing templates and make sure they still make sense

**Comment by travishathaway** [comment]
What does  it mean to be assigned to an issue? When should you? How long?

**Comment by kalawac** [comment]
I'm going to take lead in working on this
