### ISSUE TITLE
Conda-lock features missing post-graduation

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/infrastructure#681]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Conda-lock recently graduated and a few tools that we used aren't around anymore

1. Netlify (https://app.netlify.com/sites/conda-lock/overview)
		I've requested that github app to be added for conda-lock

2. Renovate (seems enabled now)

**Comment by dbast** [comment]
Can confirm that renovate is activated.

I can configure netlify for my Github user... don't see how I can configure it for the org (if that is even possible).

**Comment by dbast** [comment]
@mariusvniekerk Can you check if it works?

**Comment by mariusvniekerk** [comment]
Looks like its all good now, thanks
