### ISSUE TITLE
stale action runs into rate limit

### ISSUE THREAD

**Issue by dbast** [conda/infrastructure#683]
### What happened?

The stale actions all run at the same time and now happen to run into a rate limit.

**Comment by kenodegard** [comment]
TIL that the sync action supports [templating](https://github.com/BetaHuhn/repo-file-sync-action#using-templates) the synced files using a Jinja syntax. We should revisit all synced files to see if they could benefit from a more personalized touch (e.g. injecting different times for cron jobs, injecting the repo name, etc.).
