### ISSUE TITLE
conda-lock permission requests

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/infrastructure#686]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

@mariusvniekerk and @ocefpaf need permission to set some of the github secrets that are used to publish to PyPI

**Comment by dbast** [comment]
Authenticated users must have collaborator access to a repository to create, update, or read secrets, as stated here https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret but is not specified what level is required.

Reading this https://github.com/github/docs/issues/1087#issuecomment-1144190898 gives the indication that this should already work for both of you via API https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret  ... can you try that?

**Comment by mariusvniekerk** [comment]
i certainly can't see it at all in the UI

**Comment by mariusvniekerk** [comment]
Okay i can set them with

```shell
$ gh secret --repo conda/conda-lock set PYPI_PASSWORD --app actions
? Paste your secret **********************************************************************************************************************************************************
✓ Set Actions secret PYPI_PASSWORD for conda/conda-lock
```
