### ISSUE TITLE
Add a new User Experience label

### ISSUE THREAD

**Issue by beeankha** [conda/infrastructure#693]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Since there are a good amount of [user experience-related tickets out there](https://github.com/conda/conda/issues/12259), it might be beneficial to have a new `type::ux` or `type::user-experience` label.

**Comment by kenodegard** [comment]
I propose we use `ux`.

In theory, the `type::*` labels are supposed to be mutually exclusive and I can see `ux` being auxiliary metadata that compliments a `type::*` much like the `cli::*` labels defined in conda compliments the `type::*`.

**Comment by beeankha** [comment]
I thought about this a bit more and I agree with you, @kenodegard . The `type::*` labels should indeed be mutually exclusive, so what you're suggesting makes sense.
