### ISSUE TITLE
Add a new Deprecation label

### ISSUE THREAD

**Issue by beeankha** [conda/infrastructure#694]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Since removing deprecated features are a bit more specific than general "tech debt", perhaps we could implement a new `type::deprecation` label for issues and requests related to removing deprecated code or marking certain functions/decorators/etc as deprecated.

**Comment by kenodegard** [comment]
I concur that deprecations are something in between `type::task` and `type::tech-debt` so `type::deprecation` makes sense to me.
