### ISSUE TITLE
Clean up default configs (labels, templates) so it's not as `conda/conda` specific

### ISSUE THREAD

**Issue by jaimergp** [conda/infrastructure#699]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The current set of defauls are a bit too `conda/conda` specific for my taste. For example, in `conda/constructor` I see:

- [Labels](https://github.com/conda/constructor/labels) that should only exist in `conda/conda`; e.g. all those `hack::*` ones?
- The [bug issue template](https://github.com/conda/constructor/issues/new?assignees=&labels=type%3A%3Abug&template=0_bug.yml) requires details about a `conda` installation but nothing about `constructor`. The intro paragraphs focus on "Conda" (maybe as a community? but it's unclear and distracting).

### Why is this needed?

It is confusing for maintainers and users to be required to fill data that is irrelevant for the project.

### What should happen?

Ideally we would have a nice set of defaults that can be overridden with some mechanism of customization. Maybe templated templates (meta!), or just changing the language so it's more generic, or maintaining some of the templates per-repo.

### Additional Context

This can also be observed in other repositories like `menuinst` or `conda-standalone`

**Comment by kenodegard** [comment]
Yes, we should revisit the templates and default labels (the hack labels should probably just be all combined into one, no need to have unique ones)

I also recently learned that the sync action we use supports [templating](https://github.com/BetaHuhn/repo-file-sync-action#using-templates), so that should help us significantly with this effort.

**Comment by kenodegard** [comment]
Regarding the bug issue template, we included the conda fields assumpting that errors in downstream tools or plugins would still need the `info`, `config`, and `list` for debugging purposes.

But I can see how `menuinst` and `conda-standalone` don't need these details so we probably want a bug issue form with conda details and a separate bug issue form without conda details.
