### ISSUE TITLE
Rename sprint label

### ISSUE THREAD

**Issue by kenodegard** [conda/infrastructure#701]
### What is the idea?

Rename the `sprint` label to something more generic.

### Why is this needed?

1. We are no longer following sprints
2. The community doesn't care what kind of methodology we use to plan our work

### What should happen?

This label just needs to indicate that some work has been picked up and is now in the pipeline.

**Comment by beeankha** [comment]
Some ideas:
- `wip`
- `active`
- `in-progress`
