### ISSUE TITLE
Update duplicate labels descriptions

### ISSUE THREAD

**Issue by kenodegard** [conda/infrastructure#704]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The https://github.com/conda/infrastructure/labels/duplicate and https://github.com/conda/infrastructure/labels/duplicate%3A%3Aprimary both specify that they are for issues however they should also be used to identify duplicate PRs.

### Why is this needed?

Sometimes we get duplicate community PR submissions solving the same problem.

### What should happen?

Update duplicate labels' descriptions to specify that they can be used for both issues and PRs.

**Comment by kalawac** [comment]
Taking this on.
