### ISSUE TITLE
Revise issues workflow so that pending::feedback label updates to pending::support after any response (not just author)

### ISSUE THREAD

**Issue by kalawac** [conda/infrastructure#709]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently, the workflow only updates the labels (from `pending::feedback` to `pending::support`) if the author responds. The proposal is to update the labels if anyone responds. Also update comment on line 34 to indicate that the `support` label is being added and not the `feedback` label.

### Why is this needed?

People other than the original author may respond to add sufficient clarity to an issue. The provision of additional information should trigger us taking another look.

### What should happen?

If an issue has a `pending::feedback` label and anyone adds an additional comment, the label should switch to `pending::support`, regardless of whether the person commenting is the original comment author.

**Comment by kalawac** [comment]
I'm planning to tackle the PR for this tomorrow.

**Comment by kenodegard** [comment]
Resolved by #719
