### ISSUE TITLE
Good first issues should show up on the GitHub designated page for new contributors

### ISSUE THREAD

**Issue by kalawac** [conda/infrastructure#727]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Change the `good-first-issue` label to `good first issue` (with spaces instead of hyphens / dashes)

### Why is this needed?

GitHub's [Contribute to Open Source page](https://opensource.guide/how-to-contribute/#finding-a-project-to-contribute-to) indicates that new potential contributors should go to `github.com/<owner>/<repository>/contribute` (for example, [https://github.com/conda/conda/contribute](https://github.com/conda/conda/contribute)) to find good first issues. Currently, due to the structure of our label for good first issues, `good-first-issue`, conda's repos do not list their associated good first issues in the GitHub page meant to welcome new contributors to a repo.

### What should happen?

If we update this label to `good first issue`, the landing page for new contributors to a repo would automatically show all relevant issues as a list of good first issues that first-time contributors might work on. See, for example, [the page that welcomes new contributors to appium's appium-desktop](https://github.com/appium/appium-desktop/contribute).

### Additional Context

Thanks to DeepSource's [curated listing of repositories with good first issues](https://github.com/deepsourcelabs/good-first-issue) for helping me to figure out a label that GitHub recognizes.

**Comment by kenodegard** [comment]
This is a great find! We should also help advertise the contribute page for each repo by adding some link/button in each repo's README.md and CONTRIBUTING.md.
