### ISSUE TITLE
Bioconda CDN sync is down

### ISSUE THREAD

**Issue by dpryan79** [conda/infrastructure#785]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The CDN hasn't synced for Bioconda in roughly 24 hours. I'm rolling out updates to ~3000 packages at the moment so I imagine it's being stressed.

For testing, you can check https://anaconda.org/bioconda/ucsc-hggcpercent, which has a new version now returned by `conda search` or `mamba search`.

### Conda Info

```shell
NA
```

### Conda Config

```shell
NA
```

### Conda list

```shell
NA
```

### Additional Context

NA

**Comment by jezdez** [comment]
Thanks for your report, I've forwarded it to the infra team at Anaconda to review what's going on

**Comment by jezdez** [comment]
@dpryan79 The sync has been kicked off again, would you mind verifying if this works now?

**Comment by dpryan79** [comment]
Thanks @jezdez it seems to be back. We'll see what happens when I slam it with more packages :P

**Comment by jezdez** [comment]
We're looking into it

**Comment by jakirkham** [comment]
Is this still an issue or was this addressed?

**Comment by jezdez** [comment]
This was addresses as part of #836. Closing as duplicate.
