### ISSUE TITLE
Placeholders in e.g. RELEASE.md

### ISSUE THREAD

**Issue by dholth** [conda/infrastructure#798]
### What happened?

e.g. https://raw.githubusercontent.com/conda/infrastructure/main/.github/sync/RELEASE.md contains

`Placeholder for `{{ repo.name }} YY.M.0` release.`

and still contains `{{ repo.name }}`without substitutions in the repository.

There should be no `{{}}` in the target repositories.

**Comment by kenodegard** [comment]
Correct, we are waiting on this: https://github.com/BetaHuhn/repo-file-sync-action/pull/303

**Comment by kenodegard** [comment]
This is being resolved with the switch to the new sync workflow (see `init.yml` and `update.yml` introduced in #937). See https://github.com/conda/infrastructure/pull/975 for templating in action.
