### ISSUE TITLE
Missing packages on CDN (2hrs after upload)

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#836]
Am seeing some packages that uploaded a while back not added to the CDN. Could someone please help us investigate this?

In particular:

* `cuda-command-line-tools`
* `cuda-visual-tools`

<img width="1840" alt="Screenshot 2023-10-10 at 3 44 40 PM" src="https://github.com/conda/infrastructure/assets/3019665/68507fb2-310d-4ccd-9c03-eb00692556f2">

<img width="1840" alt="Screenshot 2023-10-10 at 3 44 32 PM" src="https://github.com/conda/infrastructure/assets/3019665/dfd28090-8a48-428b-88c7-178ff905d510">

**Comment by jakirkham** [comment]
cc @adibbley (for awareness)

**Comment by jakirkham** [comment]
cc @jezdez

**Comment by jezdez** [comment]
I've seen it, but I'm out at the moment, @chenghlee @dholth @barabo could you take a look?

**Comment by jakirkham** [comment]
Thanks Jannis! 🙏

Sorry to bug you while you are out 😞

**Comment by jakirkham** [comment]
It looks like these did eventually cleared up. Though it did take a while

<img width="1840" alt="Screenshot 2023-10-11 at 12 02 36 AM" src="https://github.com/conda/infrastructure/assets/3019665/b7477280-6f91-418e-9ff0-621890bb7d8a">

<img width="1840" alt="Screenshot 2023-10-11 at 12 03 07 AM" src="https://github.com/conda/infrastructure/assets/3019665/29d9692d-c0a0-4fdb-82de-38d945ebf0ae">

**Comment by jakirkham** [comment]
Seeing the same issue with `cuda-tools`

<img width="1840" alt="Screenshot 2023-10-11 at 12 46 39 AM" src="https://github.com/conda/infrastructure/assets/3019665/fd4a3721-58a5-4504-b32e-53a9d99caa5f">

**Comment by jakirkham** [comment]
Eventually `cuda-tools` was mirrored to CDN. Though it seems these CDN mirroring steps are starting to take quite a bit longer

**Comment by jakirkham** [comment]
Thanks Carl! 🙏

**Comment by jakirkham** [comment]
Am curious if there are any updates here

Also please let us know if you need anything from us

**Comment by jezdez** [comment]
This was mirrored, so closing.
