### ISSUE TITLE
CDN outage on conda-forge

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#869]
We are seeing a CDN outage on conda-forge. Screenshot from [conda-forge.org/status]( https://conda-forge.org/status/ ) include below. Could someone please take a look?

<img width="1840" alt="Screenshot 2024-01-16 at 3 48 46 PM" src="https://github.com/conda/infrastructure/assets/3019665/fa269b02-b083-468d-9603-343044d14a5c">

**Comment by jakirkham** [comment]
This eventually cleared after ~45mins. Still that seems like a long time

Would be good to double check things are behaving correctly

**Comment by jakirkham** [comment]
Looks like it is degrading again

<img width="1840" alt="Screenshot 2024-01-16 at 4 43 35 PM" src="https://github.com/conda/infrastructure/assets/3019665/f607e083-35e9-4f20-a29c-a5054f4e8542">

**Comment by jakirkham** [comment]
Ok this is pretty weird

Tried to load this page ( https://anaconda.org ), which redirected to ( https://anaconda.org/jakirkham/dashboard )

This resulted in the following error

<img width="1840" alt="Screenshot 2024-01-16 at 6 43 46 PM" src="https://github.com/conda/infrastructure/assets/3019665/9cea4f40-a6f2-46cb-bfd9-063fbaa2d704">

**Comment by jakirkham** [comment]
@jezdez do we know what happened here?

**Comment by stefanandres** [comment]
@jakirkham The underlying database was temporarily overloaded due to a massive amount of package uploads at the time.

**Comment by jezdez** [comment]
@jakirkham Can you confirm if this is still happening?

**Comment by jakirkham** [comment]
Thanks Stefan for the update and Jannis for checking in! 🙏

AFAICT it has stopped happening. However the odd thing about this issue was it occurred intermittently

**Comment by jezdez** [comment]
Given the additional work to improve the channel cloning functionality, I think this can be closed now. @jakirkham Please let us know in case there are intermittent issues again.
