### ISSUE TITLE
Slow CDN mirroring

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#892]
It looks like it is taking over 1hr for some packages to mirror. For example:

<img width="1840" alt="Screenshot 2024-03-05 at 11 55 44 PM" src="https://github.com/conda/infrastructure/assets/3019665/f1d0b798-9cb3-4b62-ac18-5f89148b69da">

Do we know what might be causing this?

**Comment by jakirkham** [comment]
Here's another example:

<img width="1840" alt="Screenshot 2024-03-06 at 12 23 01 AM" src="https://github.com/conda/infrastructure/assets/3019665/7721f0f6-cce2-4a00-8c3c-42261170e672">

**Comment by stefanandres** [comment]
We see some errors in the channel-clone VMs, we are checking if this is related

**Comment by jakirkham** [comment]
Thanks Stefan! 🙏

Interested to learn what you discover 🙂

**Comment by jakirkham** [comment]
Adding a more recent example in case it is helpful

<img width="1840" alt="Screenshot 2024-03-06 at 2 35 04 PM" src="https://github.com/conda/infrastructure/assets/3019665/8b5c47ba-18e3-467a-87ce-9a890c61cafd">

**Comment by jakirkham** [comment]
This one is approaching ~2.5hrs

Idk if there is something more going on with this case (hence mentioning it explicitly)

<img width="1840" alt="Screenshot 2024-03-06 at 3 43 20 PM" src="https://github.com/conda/infrastructure/assets/3019665/e566aea4-5697-483a-a893-8db32cd07311">

**Comment by h-vetinari** [comment]
Another example after John referred me to this issue: 2+ hours after marking some packages as broken in https://github.com/conda-forge/admin-requests/commit/164a4271b51ee47fdcfdd52905e0137fbdf21003, packages are still not removed from the CDN (it's difficult to do quickfixes to wide-ranging breaks like this one if the turnaround is that long).
```
>mamba repoquery search -c conda-forge gcc_linux-aarch64=12.3.0=*_2 -p linux-64

Executing the query gcc_linux-aarch64=12.3.0=*_2

conda-forge/noarch                                  13.9MB @   3.8MB/s  3.6s
conda-forge/linux-64                                33.0MB @   4.2MB/s  7.8s


 Name              Version Build        Channel     Subdir
-------------------------------------------------------------
 gcc_linux-aarch64 12.3.0  hd570763_2   conda-forge linux-64            # should be empty


>python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.Timestamp.now("utc")
Timestamp('2024-03-12 05:43:31.911276+0000', tz='UTC')                  # marked broken ~2:20h before
```

**Comment by dholth** [comment]
We see some files generated by anaconda.org's dynamic repodata like `linux-aarch64/awscli-1.29.39-py38he37f277_0.conda ` that can't be downloaded, and others like `noarch/strawberry-graphql-with-asgi-0.162.0-pyhd8ed1ab_0.conda` that cannot be re-indexed as part of the CDN process.

**Comment by jakirkham** [comment]
Interesting, thanks Daniel! 🙏

Is there something in regards to those packages specifically that looks relevant?

Or did something unrelated to those packages occur (like a network outage or running out of disk space)?

**Comment by jakirkham** [comment]
Were we able to determine the cause here?

**Comment by dholth** [comment]
We were able to find packages that have repodata but no downloadable archive [missing-packages.txt](https://github.com/conda/infrastructure/files/14655836/missing-packages.txt)

We were also able to fix a bug that is more likely to be the cause, where we would have trouble re-downloading a package in the CDN process if the first clone failed. We were not able to find the precise cause.

**Comment by jakirkham** [comment]
Gotcha thanks for the update Daniel! 🙏

Looked at the first one on the list, `linux-aarch64/awscli-1.29.39-py38he37f277_0.conda`. It looks like other OS and arch combinations for `1.29.39` had validation issues ( https://github.com/conda-forge/awscli-feedstock/issues/765#issuecomment-1702350487 ), but `linux-aarch64` was not one of these. These eventually this got sorted out. Can see a successful build and upload for this package. Here is the [attached log]( https://github.com/conda/infrastructure/files/14656481/awscli-feedstock_20230901.1_linux_aarch64_python3.8.____73_pypy.txt ). Though agree downloading this package doesn't work. So not sure what happened here. Maybe it should be marked `broken` (unclear whether that helps this issue)

The second package, `noarch/boto3-stubs-lite-1.26.89-pyhd8ed1ab_0.conda`, had a validation error with that package specifically ( https://github.com/conda-forge/boto3-stubs-lite-feedstock/issues/120#issuecomment-1465186684 ). Same with the third package, `noarch/ca-policy-lcg-1.119-hd8ed1ab_0.conda`, ( https://github.com/conda-forge/ca-policy-lcg-feedstock/issues/20#issue-1627340874 ). At least for these two cases, the conda-forge validation service notes the packages were not copied. However there do appear to be packages with `0` downloads for both [`boto3-stubs-lite`]( https://anaconda.org/conda-forge/boto3-stubs-lite/files?version=1.26.89 ) and [`ca-policy-lcg`]( https://anaconda.org/conda-forge/ca-policy-lcg/files?version=1.119 ). Visiting or downloading either results in a 404. Perhaps these should be marked `broken` as well

Looking at the latter two cases, do not see them in `http://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2`. Nor do they show up in [`conda-forge-repodata-patches`]( https://anaconda.org/conda-forge/conda-forge-repodata-patches). So am wondering how these are added to the repodata when no package was copied

Idk if we can have aborted copy with the conda-forge validation service that might generate these issues, but that seems like one question that comes out of this

cc @beckermr (in case I'm missing anything here)

**Comment by dholth** [comment]
We download the dynamic anaconda.org repodata.json beefore creating the CDN version.

**Comment by jakirkham** [comment]
Can you please remind me which URL that lives under?

**Comment by dholth** [comment]
https://conda.anaconda.org/conda-forge/noarch/repodata-clone.json e.g.

**Comment by h-vetinari** [comment]
Just saw a particularly severe case today (still nothing after 3.5h for `linux-64`, 2h for `win-64`):

![image](https://github.com/conda/infrastructure/assets/33685575/c31f5ca6-8c45-4326-899d-57f824ee301f)

**Comment by dholth** [comment]
The logs show that the CDN clone process downloaded that archive from https://conda-web.anaconda.org/conda-forge/linux-64/clangdev-18.1.2-default_h127d8a8_0.conda, had a bad archive at 2024-03-21T02:29:30 and was able to get a good archive at 2024-03-21T06:12

**Comment by h-vetinari** [comment]
Not that I pretend to understand the cloning mechanism (or the reasons why it might fail), but would it make sense to have a shorter retry loop for failed clones? Like try again immediately after, or after X minutes delay?

**Comment by dholth** [comment]
It does retry frequently, there may be an intermediate cache issue.

**Comment by beckermr** [comment]
The CDN appears to be down again.

**Comment by jaimergp** [comment]
Approaching the 500min mark 😬

**Comment by dholth** [comment]
We've addressed a disk-full issue.

**Comment by jakirkham** [comment]
Just ran into a [a network issue]( https://dev.azure.com/conda-forge/feedstock-builds/\_build/results?buildId=907880&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=717 ):

```python
conda.CondaMultiError: ('Connection broken: IncompleteRead(199522674 bytes read, 79146888 more expected)', IncompleteRead(199522674 bytes read, 79146888 more expected))
('Connection broken: IncompleteRead(199522674 bytes read, 79146888 more expected)', IncompleteRead(199522674 bytes read, 79146888 more expected))
```

Wondering if this is related

**Comment by jezdez** [comment]
> Approaching the 500min mark 😬 Should that metric be part of [anaconda.statuspage.io](https://anaconda.statuspage.io/)?

Yes, I think we should start tracking this publicly somehow

**Comment by beckermr** [comment]
CDN is at 37 minutes.

**Comment by dholth** [comment]
Should be resolved.

**Comment by jaimergp** [comment]
Last sync was done almost 10h ago now.

**Comment by jakirkham** [comment]
Looking at this case, mirroring has not completed after ~40mins

<img width="1840" alt="Screenshot 2024-04-09 at 1 09 41 PM" src="https://github.com/conda/infrastructure/assets/3019665/18578821-590a-4616-98c9-99791227e071">

**Comment by jakirkham** [comment]
The `linux-aarch64` (highlighted) and `win-64` package above it are still mirroring. Approaching the ~1.5hr mark

<img width="1840" alt="Screenshot 2024-04-09 at 4 51 16 PM" src="https://github.com/conda/infrastructure/assets/3019665/f6df2598-56ef-4e90-8300-c33410106d72">

**Comment by jakirkham** [comment]
Regarding `cuda-tools`, the `linux-aarch64` package is now available on CDN

<img width="1840" alt="Screenshot 2024-04-09 at 6 48 34 PM" src="https://github.com/conda/infrastructure/assets/3019665/1c8ba2a0-23e4-4066-942d-04646b540a3a">

However the `win-64` package is not. It has been ~3.25hrs since it was uploaded

```zsh
% conda search 'conda-forge:cuda-tools[subdir=win-64]=12.4.1'
Loading channels: done
No match found for: cuda-tools=12.4.1[subdir=win-64]. Search: *cuda-tools*=12.4.1[subdir=win-64]

PackagesNotFoundError: The following packages are not available from current channels:

  - cuda-tools=12.4.1[subdir=win-64]

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by dholth** [comment]
`CONDA_DEBUG=1 conda search 'conda-forge::cuda-tools[subdir=win-64]=12.4.1'`

**Comment by jakirkham** [comment]
Thanks Daniel! 🙏 

More details below:

<details>
<summary><code>CONDA_DEBUG=1 conda search 'conda-forge::cuda-tools[subdir=win-64]=12.4.1'</code></summary>

```zsh
% CONDA_DEBUG=1 conda search 'conda-forge::cuda-tools[subdir=win-64]=12.4.1'
DEBUG conda.gateways.logging:set_log_level(233): log_level set to 10
Loading channels: ...working... DEBUG conda.core.package_cache_data:_check_writable(321): package cache directory '/Users/jkirkham/miniforge/pkgs' writable: True
DEBUG conda.gateways.repodata:fetch_latest(827): Using cached repodata for https://conda.anaconda.org/conda-forge/win-64/repodata.json at /Users/jkirkham/miniforge/pkgs/cache/5afe41e9.json. Timeout in 1899 sec
DEBUG conda.gateways.repodata:read_cache(907): Loading raw json for https://conda.anaconda.org/conda-forge/win-64/repodata.json at /Users/jkirkham/miniforge/pkgs/cache/5afe41e9.json
done
No match found for: conda-forge/win-64::cuda-tools=12.4.1. Search: conda-forge/win-64::*cuda-tools*=12.4.1
Traceback (most recent call last):
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/conda/cli/main.py", line 83, in main_subshell
    exit_code = do_call(args, parser)
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 199, in do_call
    result = getattr(module, func_name)(args, parser)
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/conda/cli/main_search.py", line 265, in execute
    raise PackagesNotFoundError((str(spec),), channels_urls)
conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge/win-64::cuda-tools=12.4.1

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

</details>

**Comment by dholth** [comment]
Let's try reducing the cache TTL.
`CONDA_LOCAL_REPODATA_TTL=0 CONDA_DEBUG=1 conda search 'conda-forge::cuda-tools[subdir=win-64]=12.4.1' --json`

**Comment by jakirkham** [comment]
That looks promising

<details>
<summary><code>CONDA_LOCAL_REPODATA_TTL=0 CONDA_DEBUG=1 conda search 'conda-forge::cuda-tools[subdir=win-64]=12.4.1' --json</code></summary>

```
DEBUG conda.gateways.logging:set_log_level(233): log_level set to 10
DEBUG conda.core.package_cache_data:_check_writable(321): package cache directory '/Users/jkirkham/miniforge/pkgs' writable: True
DEBUG conda.gateways.repodata:fetch_latest(836): Local cache timed out for https://conda.anaconda.org/conda-forge/win-64/repodata.json at /Users/jkirkham/miniforge/pkgs/cache/5afe41e9.json
DEBUG conda.gateways.repodata.jlap.interface:__init__(41): Using ZstdRepoInterface
DEBUG conda.gateways.connection.session:add_binstar_token(247): Adding anaconda token for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json.zst>
DEBUG urllib3.connectionpool:_new_conn(1055): Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG urllib3.connectionpool:_make_request(549): https://conda.anaconda.org:443 "GET /t/ja-0b7702b5-09c2-4eba-86f1-afde7a4f059b/conda-forge/win-64/repodata.json.zst HTTP/1.1" 200 21595511
DEBUG conda.gateways.repodata.jlap.fetch:download_and_hash(243): https://conda.anaconda.org/conda-forge/win-64/repodata.json.zst {'Date': 'Wed, 10 Apr 2024 00:06:12 GMT', 'Content-Type': 'binary/octet-stream', 'Content-Length': '21595511', 'Connection': 'keep-alive', 'CF-Ray': '871e7d54f85f6b05-DFW', 'CF-Cache-Status': 'HIT', 'Accept-Ranges': 'bytes', 'Age': '624', 'Cache-Control': 'public, max-age=1200', 'ETag': '"265bb4f741e3a511d1b7fd13e0edee29"', 'Expires': 'Wed, 10 Apr 2024 00:26:12 GMT', 'Last-Modified': 'Tue, 09 Apr 2024 23:51:43 GMT', 'Vary': 'Accept-Encoding', 'x-amz-id-2': 'KsKq6Hrja0c+NuJOtbl7K2aZzL0wG6RjgNYYmQdqWpd3z3J4QGMToZG3p6uCst6RCFsGipoI7hk=', 'x-amz-request-id': '0TEK1J904ZF6JPAZ', 'x-amz-version-id': 'null', 'Set-Cookie': '__cf_bm=wiFBhoz93urWirCFc2ZG6eza4dPUj0Boq5Om5XXAAqg-1712707572-1.0.1.1-fImsderM0uAGUXTU1v5f2D6oevTo0EiN9RzvfapVIAJg8tz5A7xMZcag9R2Dk6LX_2rNKVn8hm_yraEI3GsI6RuELD2gizrmaUR0prPSIoM; path=/; expires=Wed, 10-Apr-24 00:36:12 GMT; domain=.anaconda.org; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare'}
INFO conda.gateways.repodata.jlap.fetch:download_and_hash(264): Download 21595511 bytes {'User-Agent': 'conda/24.3.0 requests/2.31.0 CPython/3.10.13 Darwin/23.4.0 OSX/14.4.1 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'if-none-match': '"6ca41bfb39370baa2abf1c3307d43f6e"'}
DEBUG conda.gateways.repodata.jlap.fetch:timeme(196): Download complete https://conda.anaconda.org/conda-forge/win-64/repodata.json Took 1.14s
INFO conda.gateways.repodata.jlap.fetch:request_url_jlap_state(431): Apply 0 patches 3796a3c1f32f8782… → 3796a3c1f32f8782…
DEBUG conda.gateways.repodata.jlap.fetch:timeme(196): Apply Patches Took 0.00s
```

```json
{
  "cuda-tools": [
    {
      "arch": null,
      "build": "h57928b3_0",
      "build_number": 0,
      "channel": "https://conda.anaconda.org/conda-forge/win-64",
      "constrains": [],
      "depends": [
        "cuda-command-line-tools 12.4.1.*",
        "cuda-visual-tools 12.4.1.*"
      ],
      "fn": "cuda-tools-12.4.1-h57928b3_0.conda",
      "license": "LicenseRef-NVIDIA-End-User-License-Agreement",
      "md5": "12168c96051bbbc85dbb96ec9a8b0fac",
      "name": "cuda-tools",
      "platform": null,
      "sha256": "720c78b89fe36e19881347d69329f0ff8c1c4cd1630d39f3147d4fe08ace8583",
      "size": 20367,
      "subdir": "win-64",
      "timestamp": 1712694515857,
      "url": "https://conda.anaconda.org/conda-forge/win-64/cuda-tools-12.4.1-h57928b3_0.conda",
      "version": "12.4.1"
    }
  ]
}
```

</details>

**Comment by jakirkham** [comment]
This case is approaching the 2hr mark, but does not appear to be picked up by CDN

Can find 1 of the 2 packages expected with `CONDA_LOCAL_REPODATA_TTL=0 CONDA_DEBUG=1 conda search 'conda-forge::cuda-toolkit=12.4.1' --json`

<img width="1840" alt="Screenshot 2024-04-09 at 11 43 24 PM" src="https://github.com/conda/infrastructure/assets/3019665/f6196160-6f08-464c-b9b9-9a558645c354">

**Comment by chenghlee** [comment]
It looks like both packages are now available:
```
$ CONDA_LOCAL_REPODATA_TTL=0 CONDA_DEBUG=1 conda search 'conda-forge::cuda-toolkit=12.4.1' --json
DEBUG conda.gateways.logging:set_log_level(233): log_level set to 10
DEBUG conda.core.package_cache_data:_check_writable(321): package cache directory '/home/chl/.miniconda3-x86_64/pkgs' writable: True
DEBUG conda.gateways.repodata:fetch_latest(836): Local cache timed out for https://conda.anaconda.org/conda-forge/linux-64/repodata.json at /home/chl/.miniconda3-x86_64/pkgs/cache/497deca9.json
DEBUG conda.gateways.repodata.jlap.interface:__init__(41): Using ZstdRepoInterface
DEBUG conda.gateways.connection.session:add_binstar_token(247): Adding anaconda token for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json.zst>
DEBUG urllib3.connectionpool:_new_conn(1052): Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG urllib3.connectionpool:_make_request(546): https://conda.anaconda.org:443 "GET /t/ch-aad2628c-7f2b-496e-98ce-4fcff0ee47b9/conda-forge/linux-64/repodata.json.zst HTTP/1.1" 304 0
DEBUG conda.gateways.repodata.jlap.fetch:download_and_hash(243): https://conda.anaconda.org/conda-forge/linux-64/repodata.json.zst {'Date': 'Wed, 10 Apr 2024 17:33:49 GMT', 'Connection': 'keep-alive', 'CF-Ray': '87247bf1db4f6c79-DFW', 'CF-Cache-Status': 'HIT', 'Age': '1269', 'Cache-Control': 'public, max-age=1200', 'ETag': '"6134ed6707255ece9635559af12210f1"', 'Expires': 'Wed, 10 Apr 2024 17:53:49 GMT', 'Last-Modified': 'Wed, 10 Apr 2024 17:12:01 GMT', 'Vary': 'Accept-Encoding', 'x-amz-id-2': 'xXMe6GDWbJycN4+8p/BlbLkrY6hf+S8S8Ej7yaJjhjhoMx0RUMMY1OaU07Gb/yxsghhefqFxJqY=', 'x-amz-request-id': '4FRF0VNSKWS1SETG', 'x-amz-version-id': 'null', 'Set-Cookie': '__cf_bm=Zd4sY9TOVRGf_xkAFGWxZt22Jf9zV1CW1ZFappB_tHA-1712770429-1.0.1.1-Whna4UmYB02PdyGWm2hAjfjtN423iI9pahjBjPvhd19Y7Xir_WzKBEVZcHl7rVbWY94oHRFp5TOQeXEby1S1WrcfKFyABRrPsIO9Fo390pE; path=/; expires=Wed, 10-Apr-24 18:03:49 GMT; domain=.anaconda.org; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare'}
INFO conda.gateways.repodata.jlap.fetch:download_and_hash(264): Download 0 bytes {'User-Agent': 'conda/24.3.0 requests/2.31.0 CPython/3.11.7 Linux/6.5.0-26-generic linuxmint/21.3 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'if-none-match': '"6134ed6707255ece9635559af12210f1"'}
DEBUG conda.gateways.repodata.jlap.fetch:timeme(196): Download complete https://conda.anaconda.org/conda-forge/linux-64/repodata.json Took 0.09s
INFO conda.gateways.repodata.jlap.fetch:request_url_jlap_state(431): Apply 0 patches 4e79e31048896620… → 4e79e31048896620…
DEBUG conda.gateways.repodata.jlap.fetch:timeme(196): Apply Patches Took 0.00s
DEBUG conda.gateways.repodata:fetch_latest(836): Local cache timed out for https://conda.anaconda.org/conda-forge/noarch/repodata.json at /home/chl/.miniconda3-x86_64/pkgs/cache/09cdf8bf.json
DEBUG conda.gateways.repodata.jlap.interface:__init__(41): Using ZstdRepoInterface
DEBUG conda.gateways.connection.session:add_binstar_token(247): Adding anaconda token for url <https://conda.anaconda.org/conda-forge/noarch/repodata.json.zst>
DEBUG urllib3.connectionpool:_new_conn(1052): Starting new HTTPS connection (2): conda.anaconda.org:443
DEBUG urllib3.connectionpool:_make_request(546): https://conda.anaconda.org:443 "GET /t/ch-aad2628c-7f2b-496e-98ce-4fcff0ee47b9/conda-forge/noarch/repodata.json.zst HTTP/1.1" 304 0
DEBUG conda.gateways.repodata.jlap.fetch:download_and_hash(243): https://conda.anaconda.org/conda-forge/noarch/repodata.json.zst {'Date': 'Wed, 10 Apr 2024 17:33:52 GMT', 'Connection': 'keep-alive', 'CF-Ray': '87247c051e116b37-DFW', 'CF-Cache-Status': 'HIT', 'Age': '1272', 'Cache-Control': 'public, max-age=1200', 'ETag': '"3605ffb16e98f38bc071ce70257c459c"', 'Expires': 'Wed, 10 Apr 2024 17:53:52 GMT', 'Last-Modified': 'Wed, 10 Apr 2024 17:12:16 GMT', 'Vary': 'Accept-Encoding', 'x-amz-id-2': 'o7PiCRiTKh0i28OBv9US4lJb8Bne90hS+dQWjje44eZ8eGKGXf3KijXyyGIqkITCOeFXcv6WIwU=', 'x-amz-request-id': '4FR2PM0C9P3JSPP4', 'x-amz-version-id': 'null', 'Server': 'cloudflare'}
INFO conda.gateways.repodata.jlap.fetch:download_and_hash(264): Download 0 bytes {'User-Agent': 'conda/24.3.0 requests/2.31.0 CPython/3.11.7 Linux/6.5.0-26-generic linuxmint/21.3 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'if-none-match': '"3605ffb16e98f38bc071ce70257c459c"', 'Cookie': '__cf_bm=Zd4sY9TOVRGf_xkAFGWxZt22Jf9zV1CW1ZFappB_tHA-1712770429-1.0.1.1-Whna4UmYB02PdyGWm2hAjfjtN423iI9pahjBjPvhd19Y7Xir_WzKBEVZcHl7rVbWY94oHRFp5TOQeXEby1S1WrcfKFyABRrPsIO9Fo390pE'}
DEBUG conda.gateways.repodata.jlap.fetch:timeme(196): Download complete https://conda.anaconda.org/conda-forge/noarch/repodata.json Took 0.10s
INFO conda.gateways.repodata.jlap.fetch:request_url_jlap_state(431): Apply 0 patches 3a8d1a3f16e02a99… → 3a8d1a3f16e02a99…
DEBUG conda.gateways.repodata.jlap.fetch:timeme(196): Apply Patches Took 0.00s
{
  "cuda-toolkit": [
    {
      "arch": null,
      "build": "h7428d3b_0",
      "build_number": 0,
      "channel": "https://conda.anaconda.org/conda-forge/noarch",
      "constrains": [],
      "depends": [
        "__win",
        "cuda-compiler 12.4.1.*",
        "cuda-libraries 12.4.1.*",
        "cuda-libraries-dev 12.4.1.*",
        "cuda-nvml-dev 12.4.127.*",
        "cuda-tools 12.4.1.*"
      ],
      "fn": "cuda-toolkit-12.4.1-h7428d3b_0.conda",
      "license": "LicenseRef-NVIDIA-End-User-License-Agreement",
      "md5": "da683653aaadbeeb5a7a2561b2464728",
      "name": "cuda-toolkit",
      "noarch": "generic",
      "package_type": "noarch_generic",
      "platform": null,
      "sha256": "3f750755a089f61fb58e6e255706bd2d010fd217fcb0a503c2de9fe3a337b247",
      "size": 20519,
      "subdir": "noarch",
      "timestamp": 1712711684371,
      "url": "https://conda.anaconda.org/conda-forge/noarch/cuda-toolkit-12.4.1-h7428d3b_0.conda",
      "version": "12.4.1"
    },
    {
      "arch": null,
      "build": "ha804496_0",
      "build_number": 0,
      "channel": "https://conda.anaconda.org/conda-forge/noarch",
      "constrains": [],
      "depends": [
        "__linux",
        "cuda-compiler 12.4.1.*",
        "cuda-libraries 12.4.1.*",
        "cuda-libraries-dev 12.4.1.*",
        "cuda-nvml-dev 12.4.127.*",
        "cuda-tools 12.4.1.*"
      ],
      "fn": "cuda-toolkit-12.4.1-ha804496_0.conda",
      "license": "LicenseRef-NVIDIA-End-User-License-Agreement",
      "md5": "e1e8cfdbb172f4b6558ce2db688e851f",
      "name": "cuda-toolkit",
      "noarch": "generic",
      "package_type": "noarch_generic",
      "platform": null,
      "sha256": "c3faecbb52cbdb82d1723e82ed572ae23bc187863b7f499f8afe7247cf1178c1",
      "size": 20097,
      "subdir": "noarch",
      "timestamp": 1712717191443,
      "url": "https://conda.anaconda.org/conda-forge/noarch/cuda-toolkit-12.4.1-ha804496_0.conda",
      "version": "12.4.1"
    }
  ]
}
```

This latest delay is most likely due to the issues with the anaconda.org backend (xref: conda/infrastructure#899). The channel cloning process relies on various calls to .org's API; the .org database was sporadically triggering the OOM (out-of-memory) killer on the backend host. Anaconda's infrastructure team has expanded memory and scaling allocation for the database backend, and that should help stabilize things again.

**Comment by dholth** [comment]
Could we write a process that periodically checks repodata-clone.json versus repodata.json to keep track of any delay between packages appearing in the former versus the latter

**Comment by jakirkham** [comment]
Thanks Cheng and Daniel! 🙏

Daniel, think that is a good idea. If there is some way to share log details or maybe graphs on resource usage, that might help as well

We were also wondering if it would make sense to have a GH template for CDN issues. Are there specific pieces of info we should be capturing that would help narrow things down?

**Comment by astrofrog** [comment]
Seeing issues today with https://anaconda.org/conda-forge/hyperion-fortran/files, not available after 2h

**Comment by jakirkham** [comment]
Am seeing this with recent `llvmlite` RC packages. These were upload ~2hrs ago. However it looks like none are available yet

<img width="1840" alt="Screenshot 2024-05-17 at 12 27 57 PM" src="https://github.com/conda/infrastructure/assets/3019665/15402730-5e07-404f-bf8e-108e7d963d33">

**Comment by jjerphan** [comment]
To know whether recent packages can be pulled, one tend to watch when the last update to the `repodata.json` was made with:

```
watch -n 1 "curl -sI https://conda.anaconda.org/conda-forge/linux-64/repodata.json | grep 'last-modified'"
```
