### ISSUE TITLE
Bioconda CDN seems to be out of sync

### ISSUE THREAD

**Issue by johanneskoester** [conda/infrastructure#895]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Seems like the bioconda CDN is out of sync. We have yesterday updated cutadapt to 4.7, but it is not findable from the client, although anaconda.org shows the current version 4.7: https://anaconda.org/bioconda/cutadapt

**Comment by johanneskoester** [comment]
@tnabtaf any chance that somebody has a look?

**Comment by jezdez** [comment]
@johanneskoester @tnabtaf has retired recently, don't hesitate to ping me instead. Thanks!

**Comment by johanneskoester** [comment]
The sync seems to be up again.

**Comment by johanneskoester** [comment]
Thanks for fixing!
