### ISSUE TITLE
Add GitHub token to `conda/constructor`

### ISSUE THREAD

**Issue by marcoesters** [conda/infrastructure#920]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The idea is to automatically report test failures when pushing to `main` as an issue at the `constructor` project similar to what is done at `conda-libmamba-solver`: https://github.com/conda/conda-libmamba-solver/blob/efa3b84141e4ff777928aaae952fac417b059091/.github/workflows/tests.yml#L680-L690

This requires a token with the permission to create issues.

### Why is this needed?

To support key-vault-based code signing tools like AzureSignTool, repository secrets are needed to do integration tests. These are not available to contributions from a fork so that these tests need to be skipped. This can cause failures when merging to `main`. For more context, see the issue at `constructor`: https://github.com/conda/constructor/issues/775

`conda-libmamba-solver` creates issues on test failures to make them more visible. The same should be done for `constructor` so that problem can be addressed promptly.

### What should happen?

A token should be added as a repository secret to `conda/constructor`.

**Comment by kenodegard** [comment]
`CONSTRUCTOR_ISSUES` repository secret created and added to conda/constructor.

**Comment by marcoesters** [comment]
Thank you! The token works
