### ISSUE TITLE
conda-forge CDN cloning last updated ~869mins ago

### ISSUE THREAD

**Issue by jakirkham** [conda/infrastructure#935]
Looks like we are running into an issue with CDN cloning for the conda-forge channel

According to the [conda-forge.org/status]( https://conda-forge.org/status/ ) page, it has been ~869mins since that last update (screenshot below):

<img width="1840" alt="Screenshot 2024-05-08 at 3 24 31 PM" src="https://github.com/conda/infrastructure/assets/3019665/0049e845-16d6-4f64-b4bd-c2544c4a938b">

xref: https://github.com/conda-forge/status/issues/176

**Comment by jakirkham** [comment]
A recent example of this is [`libtorch`]( https://anaconda.org/conda-forge/libtorch/files ). The oldest package here was uploaded ~4hrs ago and still has a download count of 0

<img width="1840" alt="Screenshot 2024-05-08 at 3 28 24 PM" src="https://github.com/conda/infrastructure/assets/3019665/11b0a157-5b8a-4e35-ba98-1d07b476a39f">

**Comment by h-vetinari** [comment]
Another example is `pyarrow-core` / `pyarrow-all` which saw their first [builds](https://anaconda.org/conda-forge/pyarrow-core/files) a few hours ago.

**Comment by jakirkham** [comment]
The conda-forge status page is now showing the CDN as having synced recently

<img width="1840" alt="Screenshot 2024-05-08 at 5 40 04 PM" src="https://github.com/conda/infrastructure/assets/3019665/f87dca5d-6ce6-4671-ae38-9315bc66d770">

<hr>

Do see some improvements with `libtorch`, but still a lot of packages are being missed

<img width="1840" alt="Screenshot 2024-05-08 at 5 40 43 PM" src="https://github.com/conda/infrastructure/assets/3019665/5ccc4e8a-5954-4936-9182-0f25e34af20d">

<hr>

IOW this is still a live issue, but it does seem like the CDN is trying to do something

**Comment by h-vetinari** [comment]
All the pyarrow-core packages have now made it through the CDN.

**Comment by jezdez** [comment]
Yes, this was a temporary problem that @dholth has fixed within the cloning system.

**Comment by jakirkham** [comment]
Thanks Jannis! 🙏

Do we know what the cause was?

**Comment by dholth** [comment]
We are working on a permanent fix that does not fill the disk.
When the clone process is working, it takes about 8-12 minutes per iteration. There may be delays in other parts of the process like anaconda.org or the CDN. Do we have a way to measure the time that individual packages take to clone?

**Comment by jakirkham** [comment]
Thanks Daniel! 🙏

Ok gotcha. So this is the disk overfilling issue we have seen before. Good to know it's a familiar issue

I don't think we have measurements collected external to Anaconda. Though I would be happy to be wrong. @wolfv or @beckermr is this something either of you have looked at before? No worries if not

Is this measured on the Anaconda side somehow?
