### ISSUE TITLE
Create CoC GH teams

### ISSUE THREAD

**Issue by kenodegard** [conda/infrastructure#974]
### What to do?

The CoC committee has an official email (conduct@conda.org) and GH bot account (@conda-conduct) but we'd also like to have a GH team allowing others to mention us in threads.

**Comment by kenodegard** [comment]
just confirmed that mentioning @conda-conduct fires off an email to conduct@conda.org

**Comment by jezdez** [comment]
@kenodegard for record keeping, could you link to the current team members?

**Comment by kenodegard** [comment]
https://github.com/conda/governance/blob/92ccbb977a1e7edce77383b7054c80c1eb9a6566/CODE_OF_CONDUCT.md?plain=1#L260-L269:

```
Eric Dill              @ericdill
Dasha Gurova           @dashagurova
Bianca Henderson       @beeankha
Katherine Kinnaman     @kathatherine
Mahe Iram Khan         @ForgottenProgramme
Ken Odegard            @kenodegard
Crystal Soja           @csoja
Jaime Rodríguez-Guerra @jaimergp
```
